### ISSUE TITLE
Issue with v1.33

### ISSUE THREAD

**Issue by holen82** [sand4rt/playwright-ct-web#10]
Hi,

after upgrading to v1.33, I get an error when trying to run tests:
```
Error: Cannot find module '@playwright/experimental-ct-core/lib/mount'
Require stack:
- C:\Git\es-web-components\node_modules\.pnpm\@sand4rt+experimental-ct-web@1.33.0_@playwright+test@1.33.0\node_modules\@sand4rt\experimental-ct-web\index.js
```
I've updated Playwright as well to v1.33 - is there anything else I need to update/do?

**Comment by sand4rt** [comment]
Hey @holen82, thanks for creating the issue! Could you verify if this is resolved in v1.33.1?
